# Generated by Django 4.1.3 on 2022-11-21 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('dni', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'usuarios',
                'verbose_name_plural': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Calibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calibre', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fundo', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presentacion', models.CharField(max_length=100)),
                ('cantidad_de_cajas', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variedad', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zona', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sede', models.CharField(max_length=50)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.zona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planta', models.CharField(max_length=100)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.sede')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=255)),
                ('dp', models.CharField(max_length=150, null=True)),
                ('plu', models.BooleanField(default=False)),
                ('completo', models.BooleanField(default=False)),
                ('cantidad_de_cajas', models.IntegerField(default=90)),
                ('calibre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.calibre')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.categoria')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.planta')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.presentacion')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.variedad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lote', models.CharField(max_length=50)),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.fundo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fundo',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.sede'),
        ),
        migrations.CreateModel(
            name='DetallePallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lote', models.CharField(max_length=255)),
                ('numero_de_guia', models.CharField(max_length=255)),
                ('numero_de_cajas', models.BigIntegerField(default=0)),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.pallet')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='planta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.planta'),
        ),
    ]
