# Generated by Django 4.1.3 on 2023-01-17 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('dni', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('LEC', 'Lector'), ('REG', 'Registrador'), ('REM', 'Remontador'), ('EMB', 'Embarcador')], default='REG', max_length=3)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'usuarios',
                'verbose_name_plural': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Calibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calibre', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inicio', models.DateField()),
                ('state', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Campaña',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destino', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etiqueta', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fundo', models.CharField(max_length=100)),
                ('codigo_lugar_produccion', models.CharField(max_length=150, verbose_name='Codigo de Lugar de Producción')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_caja', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Caja',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zona', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(default='RG', max_length=3)),
                ('variedad', models.CharField(max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.producto')),
            ],
            options={
                'verbose_name_plural': 'Variedades',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sede', models.CharField(max_length=50)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.zona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peso', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cantidad_de_cajas', models.IntegerField(default=100)),
                ('productos', models.ManyToManyField(to='pallet_register.producto')),
                ('tipo_caja', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.tipocaja')),
            ],
            options={
                'verbose_name_plural': 'Presentaciones',
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planta', models.CharField(max_length=100)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.sede')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=255)),
                ('codigo_comercial', models.CharField(max_length=50)),
                ('completo', models.BooleanField(default=False)),
                ('embarcado', models.BooleanField(default=False)),
                ('cantidad_de_cajas', models.IntegerField(default=90)),
                ('calibre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.calibre')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.campaign', verbose_name='Campaña')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.categoria')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.etiqueta')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.presentacion')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.variedad')),
            ],
            options={
                'get_latest_by': 'order_date',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lote', models.CharField(max_length=50)),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.fundo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fundo',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.sede'),
        ),
        migrations.CreateModel(
            name='DetallePallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dia_de_proceso', models.IntegerField(default=1)),
                ('numero_de_cajas', models.BigIntegerField(default=0)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.lote')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.pallet')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrentCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(limit_choices_to={'state': True}, on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.campaign', verbose_name='Campaña')),
            ],
            options={
                'verbose_name': 'Campaña Actual',
                'verbose_name_plural': 'Campañas Actuales',
                'get_latest_by': '-inicio',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.CharField(max_length=150)),
                ('destino', models.ManyToManyField(to='pallet_register.destino')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='etiquetas',
            field=models.ManyToManyField(to='pallet_register.etiqueta'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.planta'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='presentaciones',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='producto', chained_model_field='productos', horizontal=True, to='pallet_register.presentacion'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.producto'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='usuarios',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='planta', chained_model_field='planta', horizontal=True, to=settings.AUTH_USER_MODEL, verbose_name='Personal'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='variedades',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='producto', chained_model_field='producto', horizontal=True, to='pallet_register.variedad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='planta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.planta'),
        ),
    ]
