# Generated by Django 4.1.3 on 2023-01-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallet_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('LEC', 'Lector'), ('REG', 'Registrador'), ('REM', 'Remontador'), ('EMB', 'Embarcador')], default='REG', max_length=3),
        ),
    ]
