# Generated by Django 4.1.3 on 2023-02-04 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallet_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad_de_pallets', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.campaign')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuiaDeRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=15)),
                ('imagen', models.ImageField(upload_to='images/guia_de_remision/')),
                ('embarcado', models.BooleanField(default=False)),
                ('codigo_comercial', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.codigocomercial')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.destino')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
