# Generated by Django 4.1.3 on 2022-12-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallet_register', '0004_remove_presentacion_producto_variedad_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destino', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='lote',
            name='producto',
        ),
        migrations.AddField(
            model_name='lote',
            name='codigo_lugar_produccion',
            field=models.CharField(default='001', max_length=150, verbose_name='Codigo de Lugar de Producción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentacion',
            name='descripcion',
            field=models.CharField(default='', max_length=255, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='productos',
            field=models.ManyToManyField(to='pallet_register.producto'),
        ),
        migrations.AddField(
            model_name='variedad',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.producto'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='destino',
        ),
        migrations.AddField(
            model_name='cliente',
            name='destino',
            field=models.ManyToManyField(to='pallet_register.destino'),
        ),
    ]
