# Generated by Django 4.1.3 on 2022-12-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallet_register', '0005_destino_remove_lote_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepallet',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pallet_register.lote'),
        ),
    ]
